# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e7c945d815ba7c7502e46f4cb61f0215e748d6faf0cb46c161e70ecb833cec0ee47f05ebf18a60d50fcfe1153af51a1d509310006cd174e3adf4a35bfd070ed4

test:
  secret_key_base: 96acefb72e0ea4582aaba50ba83859d2e98c8013cc74f690e30c726bf0f1916aea5673655dfa9c5e3c13f235d99d1ec343517ce5019538d9312f91dc395ebbbc

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
